name: rl
channels:
  - defaults
dependencies:
  - joblib
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.8
  - scikit-learn
  - scipy
  - pip:
    - pygame
    - gym
    - simpy
